#-------------------------------
# General Site Settings

title: Nik Steel
description: Software Developer // Audio Engineer
email: nikolassteel@gmail.com

# NOTE: The Logo and Background image are defined in layout.yml

menu:
- {name: About, url: '#about'}
- {name: Work, url: '#work'}
- {name: Testimonials, url: '#testimonials'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Nik is an emerging software developer with audio engineering expertise.'
  rel-author: 'https://plus.google.com/u/0/+niksteel/'
  rel-publisher: 'https://plus.google.com/u/0/+niksteel/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in layout.yml

blurb: >
  **Nik is a creative problem solver.**
  He presently volunteers at [Hackforge](http://hackf.org/){:target="_blank"}, a maker space in Windsor, where he has introduced kids to 
  the [physics of sound](https://youtu.be/aO8OiT28mew?list=PLK85ZLdkWlf9xbErDN42zK4v6b1Sabhl_){:target="_blank"}, 
  topics in artificial intelligence, and fun, technology-inspired crafts projects.
  As he launches his career in software development, he is seeking opportunities to contribute to technology
  projects of any size or budget.  His uniquely diverse history in audio engineering, music, and the visual arts
  are an asset for brainstorming and collaborating with creative professionals.


skills:
- {name: Communication, value: '8'}
- {name: Leadership, value: '8'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '7'}
- {name: Team Work, value: '9'}
- {name: C / C++, value: '9'}
- {name: HTML5 / CSS3 / Javascript, value: '6'}
- {name: Acoustics, value: '9'}

#-------------------------------
# Work Section

projects:
- {name: Fruitbots, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: GeekOS, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Genetic Algorithm, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Ergodox Keyboard, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Acoustic Zoo Student Club, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Austin DIY Ribbon Mic, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Cymatics + LEAP Motion, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: ISO3382 Reverb Time Measurment, folder: 'proj-8', file: 'work/proj-8.html'}

#-------------------------------
# Testimonials Section

clients:
- {avatar: 'face-doug.jpg',
  name: 'Doug Sartori',
  title: 'Hackforge President',
  quote: '<p>As a volunteer with Hackforge Nik has used his energy, creativity and talent to help his community. It is rare to find someone who can contribute at a high level both artistically and technically. Nik has that ability.</p>',
  logo: 'hackforgelogo.png'}
- {avatar: 'face-trevor.jpg',
  name: 'Trevor Pittman',
  title: 'Operations Manager/Concert Producer - University of Windsor School of Creative Arts',
  quote: "Nik is dedicated, resourceful and keen to find out more about his area. He has put together the first-ever student electroacoustic music group and continues to work on interesting collaborative projects.",
  logo: 'uwinlogo.png'}
- {avatar: 'face-sarah.jpg',
  name: 'Sarah Morris',
  title: 'Program Coordinator at Windsor Hackforge',
  quote: "<p>Nik Steel's <strong>creativity, intelligence, and talent</strong> has been an invaluable asset at Hackforge. He has volunteered his time creating and hosting interactive programming for our tech nonprofit, including cymatics rig demonstrations and kalimba workshops.</p>",
  logo: 'hackforgelogo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/niksteel'}
- {icon: 'twitter', link: 'https://twitter.com/nik_steel'}
- {icon: 'google-plus', link: 'https://google.com/+niksteel'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/niksteel'}
- {icon: 'youtube', link: 'https://www.youtube.com/c/niksteel'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
